"""fix enum

Revision ID: 80d77dd5226e
Revises: d6e6f92246bb
Create Date: 2025-12-08 15:04:22.818730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d77dd5226e'
down_revision: Union[str, Sequence[str], None] = 'd6e6f92246bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('appname', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('feature', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'priority')
    op.drop_column('emails', 'feature')
    op.drop_column('emails', 'appname')
    # ### end Alembic commands ###
