"""Initial email table

Revision ID: 9e8626cf59c6
Revises: 
Create Date: 2025-12-04 14:50:29.561226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8626cf59c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('attachment_path', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('emails', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_emails_email'), table_name='emails')
    op.drop_column('emails', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_emails_email'), 'emails', ['email'], unique=True)
    op.drop_column('emails', 'updated_at')
    op.drop_column('emails', 'created_at')
    op.drop_column('emails', 'attachment_path')
    # ### end Alembic commands ###
