"""add appname feature priority and timestamps

Revision ID: d6e6f92246bb
Revises: 2f6f6ee80108
Create Date: 2025-12-08 12:14:56.656372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e6f92246bb'
down_revision: Union[str, Sequence[str], None] = '2f6f6ee80108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
